// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type Options as ClientOptions,
	type TDataShape,
	urlSearchParamsBodySerializer,
} from "./client";
import { client as _heyApiClient } from "./client.gen";
import type {
	CreateCaseApiV1CasesPostData,
	CreateCaseApiV1CasesPostErrors,
	CreateCaseApiV1CasesPostResponses,
	CreateItemApiV1ItemsPostData,
	CreateItemApiV1ItemsPostErrors,
	CreateItemApiV1ItemsPostResponses,
	CreateUserApiV1PrivateUsersPostData,
	CreateUserApiV1PrivateUsersPostErrors,
	CreateUserApiV1PrivateUsersPostResponses,
	CreateUserApiV1UsersPostData,
	CreateUserApiV1UsersPostErrors,
	CreateUserApiV1UsersPostResponses,
	DeleteCaseApiV1CasesIdDeleteData,
	DeleteCaseApiV1CasesIdDeleteErrors,
	DeleteCaseApiV1CasesIdDeleteResponses,
	DeleteItemApiV1ItemsIdDeleteData,
	DeleteItemApiV1ItemsIdDeleteErrors,
	DeleteItemApiV1ItemsIdDeleteResponses,
	DeleteUserApiV1UsersUserIdDeleteData,
	DeleteUserApiV1UsersUserIdDeleteErrors,
	DeleteUserApiV1UsersUserIdDeleteResponses,
	DeleteUserMeApiV1UsersMeDeleteData,
	DeleteUserMeApiV1UsersMeDeleteResponses,
	GetProductionDashboardApiV1ProductionDashboardGetData,
	GetProductionDashboardApiV1ProductionDashboardGetErrors,
	GetProductionDashboardApiV1ProductionDashboardGetResponses,
	HealthCheckApiV1UtilsHealthCheckGetData,
	HealthCheckApiV1UtilsHealthCheckGetResponses,
	LoginAccessTokenApiV1LoginAccessTokenPostData,
	LoginAccessTokenApiV1LoginAccessTokenPostErrors,
	LoginAccessTokenApiV1LoginAccessTokenPostResponses,
	PingTestApiV1UtilsTestPingGetData,
	PingTestApiV1UtilsTestPingGetResponses,
	ReadAnomaliesApiV1AnomaliesGetData,
	ReadAnomaliesApiV1AnomaliesGetErrors,
	ReadAnomaliesApiV1AnomaliesGetResponses,
	ReadCaseApiV1CasesIdGetData,
	ReadCaseApiV1CasesIdGetErrors,
	ReadCaseApiV1CasesIdGetResponses,
	ReadCasesApiV1CasesGetData,
	ReadCasesApiV1CasesGetErrors,
	ReadCasesApiV1CasesGetResponses,
	ReadItemApiV1ItemsIdGetData,
	ReadItemApiV1ItemsIdGetErrors,
	ReadItemApiV1ItemsIdGetResponses,
	ReadItemsApiV1ItemsGetData,
	ReadItemsApiV1ItemsGetErrors,
	ReadItemsApiV1ItemsGetResponses,
	ReadProductionLinesApiV1ProductionLinesGetData,
	ReadProductionLinesApiV1ProductionLinesGetErrors,
	ReadProductionLinesApiV1ProductionLinesGetResponses,
	ReadProductionOverviewApiV1ProductionOverviewGetData,
	ReadProductionOverviewApiV1ProductionOverviewGetResponses,
	ReadUserByIdApiV1UsersUserIdGetData,
	ReadUserByIdApiV1UsersUserIdGetErrors,
	ReadUserByIdApiV1UsersUserIdGetResponses,
	ReadUserMeApiV1UsersMeGetData,
	ReadUserMeApiV1UsersMeGetResponses,
	ReadUsersApiV1UsersGetData,
	ReadUsersApiV1UsersGetErrors,
	ReadUsersApiV1UsersGetResponses,
	RecoverPasswordApiV1PasswordRecoveryEmailPostData,
	RecoverPasswordApiV1PasswordRecoveryEmailPostErrors,
	RecoverPasswordApiV1PasswordRecoveryEmailPostResponses,
	RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData,
	RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostErrors,
	RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponses,
	RegisterUserApiV1UsersSignupPostData,
	RegisterUserApiV1UsersSignupPostErrors,
	RegisterUserApiV1UsersSignupPostResponses,
	ResetPasswordApiV1ResetPasswordPostData,
	ResetPasswordApiV1ResetPasswordPostErrors,
	ResetPasswordApiV1ResetPasswordPostResponses,
	SelectSolutionApiV1SolutionsIdSelectPostData,
	SelectSolutionApiV1SolutionsIdSelectPostErrors,
	SelectSolutionApiV1SolutionsIdSelectPostResponses,
	TestEmailApiV1UtilsTestEmailPostData,
	TestEmailApiV1UtilsTestEmailPostErrors,
	TestEmailApiV1UtilsTestEmailPostResponses,
	TestTokenApiV1LoginTestTokenPostData,
	TestTokenApiV1LoginTestTokenPostResponses,
	TriggerDiagnosisApiV1AnomaliesIdDiagnosePostData,
	TriggerDiagnosisApiV1AnomaliesIdDiagnosePostErrors,
	TriggerDiagnosisApiV1AnomaliesIdDiagnosePostResponses,
	UpdateCaseApiV1CasesIdPatchData,
	UpdateCaseApiV1CasesIdPatchErrors,
	UpdateCaseApiV1CasesIdPatchResponses,
	UpdateItemApiV1ItemsIdPutData,
	UpdateItemApiV1ItemsIdPutErrors,
	UpdateItemApiV1ItemsIdPutResponses,
	UpdatePasswordMeApiV1UsersMePasswordPatchData,
	UpdatePasswordMeApiV1UsersMePasswordPatchErrors,
	UpdatePasswordMeApiV1UsersMePasswordPatchResponses,
	UpdateUserApiV1UsersUserIdPatchData,
	UpdateUserApiV1UsersUserIdPatchErrors,
	UpdateUserApiV1UsersUserIdPatchResponses,
	UpdateUserMeApiV1UsersMePatchData,
	UpdateUserMeApiV1UsersMePatchErrors,
	UpdateUserMeApiV1UsersMePatchResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Login Access Token
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginAccessTokenApiV1LoginAccessTokenPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<LoginAccessTokenApiV1LoginAccessTokenPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		LoginAccessTokenApiV1LoginAccessTokenPostResponses,
		LoginAccessTokenApiV1LoginAccessTokenPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: "/api/v1/login/access-token",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Test Token
 * Test access token
 */
export const testTokenApiV1LoginTestTokenPost = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<TestTokenApiV1LoginTestTokenPostData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		TestTokenApiV1LoginTestTokenPostResponses,
		unknown,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/login/test-token",
		...options,
	});
};

/**
 * Recover Password
 * Password Recovery
 */
export const recoverPasswordApiV1PasswordRecoveryEmailPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		RecoverPasswordApiV1PasswordRecoveryEmailPostData,
		ThrowOnError
	>,
) => {
	return (options.client ?? _heyApiClient).post<
		RecoverPasswordApiV1PasswordRecoveryEmailPostResponses,
		RecoverPasswordApiV1PasswordRecoveryEmailPostErrors,
		ThrowOnError
	>({
		url: "/api/v1/password-recovery/{email}",
		...options,
	});
};

/**
 * Reset Password
 * Reset password
 */
export const resetPasswordApiV1ResetPasswordPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ResetPasswordApiV1ResetPasswordPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		ResetPasswordApiV1ResetPasswordPostResponses,
		ResetPasswordApiV1ResetPasswordPostErrors,
		ThrowOnError
	>({
		url: "/api/v1/reset-password/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Recover Password Html Content
 * HTML Content for Password Recovery
 */
export const recoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPost =
	<ThrowOnError extends boolean = false>(
		options: Options<
			RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData,
			ThrowOnError
		>,
	) => {
		return (options.client ?? _heyApiClient).post<
			RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponses,
			RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostErrors,
			ThrowOnError
		>({
			security: [
				{
					scheme: "bearer",
					type: "http",
				},
			],
			url: "/api/v1/password-recovery-html-content/{email}",
			...options,
		});
	};

/**
 * Read Users
 * Retrieve users.
 */
export const readUsersApiV1UsersGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadUsersApiV1UsersGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadUsersApiV1UsersGetResponses,
		ReadUsersApiV1UsersGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/",
		...options,
	});
};

/**
 * Create User
 * Create new user.
 */
export const createUserApiV1UsersPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateUserApiV1UsersPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateUserApiV1UsersPostResponses,
		CreateUserApiV1UsersPostErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete User Me
 * Delete own user.
 */
export const deleteUserMeApiV1UsersMeDelete = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<DeleteUserMeApiV1UsersMeDeleteData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).delete<
		DeleteUserMeApiV1UsersMeDeleteResponses,
		unknown,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/me",
		...options,
	});
};

/**
 * Read User Me
 * Get current user.
 */
export const readUserMeApiV1UsersMeGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadUserMeApiV1UsersMeGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadUserMeApiV1UsersMeGetResponses,
		unknown,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/me",
		...options,
	});
};

/**
 * Update User Me
 * Update own user.
 */
export const updateUserMeApiV1UsersMePatch = <
	ThrowOnError extends boolean = false,
>(
	options: Options<UpdateUserMeApiV1UsersMePatchData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateUserMeApiV1UsersMePatchResponses,
		UpdateUserMeApiV1UsersMePatchErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/me",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Update Password Me
 * Update own password.
 */
export const updatePasswordMeApiV1UsersMePasswordPatch = <
	ThrowOnError extends boolean = false,
>(
	options: Options<UpdatePasswordMeApiV1UsersMePasswordPatchData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdatePasswordMeApiV1UsersMePasswordPatchResponses,
		UpdatePasswordMeApiV1UsersMePasswordPatchErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/me/password",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Register User
 * Create new user without the need to be logged in.
 */
export const registerUserApiV1UsersSignupPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<RegisterUserApiV1UsersSignupPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		RegisterUserApiV1UsersSignupPostResponses,
		RegisterUserApiV1UsersSignupPostErrors,
		ThrowOnError
	>({
		url: "/api/v1/users/signup",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete User
 * Delete a user.
 */
export const deleteUserApiV1UsersUserIdDelete = <
	ThrowOnError extends boolean = false,
>(
	options: Options<DeleteUserApiV1UsersUserIdDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteUserApiV1UsersUserIdDeleteResponses,
		DeleteUserApiV1UsersUserIdDeleteErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/{user_id}",
		...options,
	});
};

/**
 * Read User By Id
 * Get a specific user by id.
 */
export const readUserByIdApiV1UsersUserIdGet = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ReadUserByIdApiV1UsersUserIdGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		ReadUserByIdApiV1UsersUserIdGetResponses,
		ReadUserByIdApiV1UsersUserIdGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/{user_id}",
		...options,
	});
};

/**
 * Update User
 * Update a user.
 */
export const updateUserApiV1UsersUserIdPatch = <
	ThrowOnError extends boolean = false,
>(
	options: Options<UpdateUserApiV1UsersUserIdPatchData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateUserApiV1UsersUserIdPatchResponses,
		UpdateUserApiV1UsersUserIdPatchErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/users/{user_id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Test Email
 * Test emails.
 */
export const testEmailApiV1UtilsTestEmailPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<TestEmailApiV1UtilsTestEmailPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		TestEmailApiV1UtilsTestEmailPostResponses,
		TestEmailApiV1UtilsTestEmailPostErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/utils/test-email/",
		...options,
	});
};

/**
 * Health Check
 */
export const healthCheckApiV1UtilsHealthCheckGet = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<HealthCheckApiV1UtilsHealthCheckGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		HealthCheckApiV1UtilsHealthCheckGetResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/v1/utils/health-check/",
		...options,
	});
};

/**
 * Ping Test
 * Simple ping test endpoint for frontend connectivity verification.
 */
export const pingTestApiV1UtilsTestPingGet = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<PingTestApiV1UtilsTestPingGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		PingTestApiV1UtilsTestPingGetResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/v1/utils/test/ping",
		...options,
	});
};

/**
 * Read Items
 * Retrieve items.
 */
export const readItemsApiV1ItemsGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadItemsApiV1ItemsGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadItemsApiV1ItemsGetResponses,
		ReadItemsApiV1ItemsGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/items/",
		...options,
	});
};

/**
 * Create Item
 * Create new item.
 */
export const createItemApiV1ItemsPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateItemApiV1ItemsPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateItemApiV1ItemsPostResponses,
		CreateItemApiV1ItemsPostErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/items/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete Item
 * Delete an item.
 */
export const deleteItemApiV1ItemsIdDelete = <
	ThrowOnError extends boolean = false,
>(
	options: Options<DeleteItemApiV1ItemsIdDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteItemApiV1ItemsIdDeleteResponses,
		DeleteItemApiV1ItemsIdDeleteErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/items/{id}",
		...options,
	});
};

/**
 * Read Item
 * Get item by ID.
 */
export const readItemApiV1ItemsIdGet = <ThrowOnError extends boolean = false>(
	options: Options<ReadItemApiV1ItemsIdGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		ReadItemApiV1ItemsIdGetResponses,
		ReadItemApiV1ItemsIdGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/items/{id}",
		...options,
	});
};

/**
 * Update Item
 * Update an item.
 */
export const updateItemApiV1ItemsIdPut = <ThrowOnError extends boolean = false>(
	options: Options<UpdateItemApiV1ItemsIdPutData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		UpdateItemApiV1ItemsIdPutResponses,
		UpdateItemApiV1ItemsIdPutErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/items/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Read Production Lines
 * Retrieve production lines.
 */
export const readProductionLinesApiV1ProductionLinesGet = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		ReadProductionLinesApiV1ProductionLinesGetData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadProductionLinesApiV1ProductionLinesGetResponses,
		ReadProductionLinesApiV1ProductionLinesGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/production/lines",
		...options,
	});
};

/**
 * Read Production Overview
 * Retrieve production overview statistics.
 */
export const readProductionOverviewApiV1ProductionOverviewGet = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		ReadProductionOverviewApiV1ProductionOverviewGetData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadProductionOverviewApiV1ProductionOverviewGetResponses,
		unknown,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/production/overview",
		...options,
	});
};

/**
 * Get Production Dashboard
 * 获取生产数据汇总dashboard
 */
export const getProductionDashboardApiV1ProductionDashboardGet = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		GetProductionDashboardApiV1ProductionDashboardGetData,
		ThrowOnError
	>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetProductionDashboardApiV1ProductionDashboardGetResponses,
		GetProductionDashboardApiV1ProductionDashboardGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/production/dashboard",
		...options,
	});
};

/**
 * Read Anomalies
 * Retrieve anomalies.
 */
export const readAnomaliesApiV1AnomaliesGet = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<ReadAnomaliesApiV1AnomaliesGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadAnomaliesApiV1AnomaliesGetResponses,
		ReadAnomaliesApiV1AnomaliesGetErrors,
		ThrowOnError
	>({
		url: "/api/v1/anomalies/",
		...options,
	});
};

/**
 * Trigger Diagnosis
 * Trigger diagnosis for an anomaly.
 */
export const triggerDiagnosisApiV1AnomaliesIdDiagnosePost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		TriggerDiagnosisApiV1AnomaliesIdDiagnosePostData,
		ThrowOnError
	>,
) => {
	return (options.client ?? _heyApiClient).post<
		TriggerDiagnosisApiV1AnomaliesIdDiagnosePostResponses,
		TriggerDiagnosisApiV1AnomaliesIdDiagnosePostErrors,
		ThrowOnError
	>({
		url: "/api/v1/anomalies/{id}/diagnose",
		...options,
	});
};

/**
 * Select Solution
 * Select a solution and create a work order.
 */
export const selectSolutionApiV1SolutionsIdSelectPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<SelectSolutionApiV1SolutionsIdSelectPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		SelectSolutionApiV1SolutionsIdSelectPostResponses,
		SelectSolutionApiV1SolutionsIdSelectPostErrors,
		ThrowOnError
	>({
		url: "/api/v1/solutions/{id}/select",
		...options,
	});
};

/**
 * Read Cases
 * Retrieve cases from the library.
 */
export const readCasesApiV1CasesGet = <ThrowOnError extends boolean = false>(
	options?: Options<ReadCasesApiV1CasesGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ReadCasesApiV1CasesGetResponses,
		ReadCasesApiV1CasesGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/cases/",
		...options,
	});
};

/**
 * Create Case
 * Create a new case in the library.
 */
export const createCaseApiV1CasesPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateCaseApiV1CasesPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateCaseApiV1CasesPostResponses,
		CreateCaseApiV1CasesPostErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/cases/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete Case
 * Delete a case.
 */
export const deleteCaseApiV1CasesIdDelete = <
	ThrowOnError extends boolean = false,
>(
	options: Options<DeleteCaseApiV1CasesIdDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteCaseApiV1CasesIdDeleteResponses,
		DeleteCaseApiV1CasesIdDeleteErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/cases/{id}",
		...options,
	});
};

/**
 * Read Case
 * Get a specific case by ID.
 */
export const readCaseApiV1CasesIdGet = <ThrowOnError extends boolean = false>(
	options: Options<ReadCaseApiV1CasesIdGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		ReadCaseApiV1CasesIdGetResponses,
		ReadCaseApiV1CasesIdGetErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/cases/{id}",
		...options,
	});
};

/**
 * Update Case
 * Update a case.
 */
export const updateCaseApiV1CasesIdPatch = <
	ThrowOnError extends boolean = false,
>(
	options: Options<UpdateCaseApiV1CasesIdPatchData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		UpdateCaseApiV1CasesIdPatchResponses,
		UpdateCaseApiV1CasesIdPatchErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "bearer",
				type: "http",
			},
		],
		url: "/api/v1/cases/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Create User
 * Create a new user.
 */
export const createUserApiV1PrivateUsersPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<CreateUserApiV1PrivateUsersPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateUserApiV1PrivateUsersPostResponses,
		CreateUserApiV1PrivateUsersPostErrors,
		ThrowOnError
	>({
		url: "/api/v1/private/users/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};
