// This file is auto-generated by @hey-api/openapi-ts

export type Anomaly = {
    line_id: string;
    station_id: string;
    defect_type: string;
    severity: string;
    detected_at: string;
    status?: string;
    assigned_to?: (string | null);
    root_cause?: (string | null);
    solution_id?: (string | null);
    id?: string;
    created_at?: string;
    closed_at?: (string | null);
};

export type Body_login_access_token_api_v1_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CaseLibrary = {
    anomaly_id: string;
    problem_description?: (string | null);
    solution_adopted?: (string | null);
    lessons_learned?: (string | null);
    id?: string;
    diagnosis_result?: ({
    [key: string]: unknown;
} | null);
    expected_effect?: ({
    [key: string]: unknown;
} | null);
    actual_effect?: ({
    [key: string]: unknown;
} | null);
    tags?: Array<(string)>;
    created_at?: string;
};

export type CaseLibraryBase = {
    anomaly_id: string;
    problem_description?: (string | null);
    solution_adopted?: (string | null);
    lessons_learned?: (string | null);
};

export type DiagnosisPublic = {
    anomaly_id: string;
    root_cause?: (string | null);
    confidence?: (number | null);
    id: string;
    created_at: string;
    solutions?: Array<SolutionPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    username: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductionLine = {
    line_name: string;
    factory_id: string;
    status?: string;
    current_status?: string;
    id?: string;
    current_plan_id?: (string | null);
    bottleneck_station_id?: (string | null);
    last_updated?: string;
    created_at?: string;
    updated_at?: string;
};

export type SolutionPublic = {
    anomaly_id: string;
    solution_type?: (string | null);
    solution_name: string;
    description?: (string | null);
    estimated_downtime_hours?: (number | null);
    success_rate?: (number | null);
    expected_loss?: (number | null);
    roi?: (number | null);
    recommended?: boolean;
    id: string;
    diagnosis_id: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    phone?: (string | null);
    role?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    phone?: (string | null);
    role?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    username?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    phone?: (string | null);
    role?: (string | null);
    is_active?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkOrder = {
    solution_id: string;
    order_type?: (string | null);
    responsible_person?: (string | null);
    instructions?: (string | null);
    estimated_duration_hours?: (number | null);
    actual_duration_hours?: (number | null);
    status?: string;
    execution_result?: (string | null);
    actual_loss?: (number | null);
    notes?: (string | null);
    id?: string;
    created_at?: string;
    started_at?: (string | null);
    completed_at?: (string | null);
};

export type ReadAnomaliesApiV1AnomaliesGetData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ReadAnomaliesApiV1AnomaliesGetResponse = (Array<Anomaly>);

export type TriggerDiagnosisApiV1AnomaliesIdDiagnosePostData = {
    id: string;
};

export type TriggerDiagnosisApiV1AnomaliesIdDiagnosePostResponse = (DiagnosisPublic);

export type ReadCasesApiV1CasesGetData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ReadCasesApiV1CasesGetResponse = (Array<CaseLibrary>);

export type CreateCaseApiV1CasesPostData = {
    requestBody: CaseLibraryBase;
};

export type CreateCaseApiV1CasesPostResponse = (CaseLibrary);

export type ReadCaseApiV1CasesIdGetData = {
    id: string;
};

export type ReadCaseApiV1CasesIdGetResponse = (CaseLibrary);

export type UpdateCaseApiV1CasesIdPatchData = {
    id: string;
    requestBody: CaseLibraryBase;
};

export type UpdateCaseApiV1CasesIdPatchResponse = (CaseLibrary);

export type DeleteCaseApiV1CasesIdDeleteData = {
    id: string;
};

export type DeleteCaseApiV1CasesIdDeleteResponse = (Message);

export type ReadItemsApiV1ItemsGetData = {
    limit?: number;
    skip?: number;
};

export type ReadItemsApiV1ItemsGetResponse = (ItemsPublic);

export type CreateItemApiV1ItemsPostData = {
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemPublic);

export type ReadItemApiV1ItemsIdGetData = {
    id: string;
};

export type ReadItemApiV1ItemsIdGetResponse = (ItemPublic);

export type UpdateItemApiV1ItemsIdPutData = {
    id: string;
    requestBody: ItemUpdate;
};

export type UpdateItemApiV1ItemsIdPutResponse = (ItemPublic);

export type DeleteItemApiV1ItemsIdDeleteData = {
    id: string;
};

export type DeleteItemApiV1ItemsIdDeleteResponse = (Message);

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_login_access_token_post;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = (Token);

export type TestTokenApiV1LoginTestTokenPostResponse = (UserPublic);

export type RecoverPasswordApiV1PasswordRecoveryEmailPostData = {
    email: string;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponse = (Message);

export type ResetPasswordApiV1ResetPasswordPostData = {
    requestBody: NewPassword;
};

export type ResetPasswordApiV1ResetPasswordPostResponse = (Message);

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData = {
    email: string;
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponse = (string);

export type CreateUserApiV1PrivateUsersPostData = {
    requestBody: PrivateUserCreate;
};

export type CreateUserApiV1PrivateUsersPostResponse = (UserPublic);

export type ReadProductionLinesApiV1ProductionLinesGetData = {
    limit?: number;
    skip?: number;
};

export type ReadProductionLinesApiV1ProductionLinesGetResponse = (Array<ProductionLine>);

export type ReadProductionOverviewApiV1ProductionOverviewGetResponse = (unknown);

export type SelectSolutionApiV1SolutionsIdSelectPostData = {
    id: string;
};

export type SelectSolutionApiV1SolutionsIdSelectPostResponse = (WorkOrder);

export type ReadUsersApiV1UsersGetData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersApiV1UsersGetResponse = (UsersPublic);

export type CreateUserApiV1UsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserApiV1UsersPostResponse = (UserPublic);

export type ReadUserMeApiV1UsersMeGetResponse = (UserPublic);

export type DeleteUserMeApiV1UsersMeDeleteResponse = (Message);

export type UpdateUserMeApiV1UsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeApiV1UsersMePatchResponse = (UserPublic);

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = (Message);

export type RegisterUserApiV1UsersSignupPostData = {
    requestBody: UserRegister;
};

export type RegisterUserApiV1UsersSignupPostResponse = (UserPublic);

export type ReadUserByIdApiV1UsersUserIdGetData = {
    userId: string;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = (UserPublic);

export type UpdateUserApiV1UsersUserIdPatchData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UpdateUserApiV1UsersUserIdPatchResponse = (UserPublic);

export type DeleteUserApiV1UsersUserIdDeleteData = {
    userId: string;
};

export type DeleteUserApiV1UsersUserIdDeleteResponse = (Message);

export type TestEmailApiV1UtilsTestEmailPostData = {
    emailTo: string;
};

export type TestEmailApiV1UtilsTestEmailPostResponse = (Message);

export type HealthCheckApiV1UtilsHealthCheckGetResponse = (boolean);

export type PingTestApiV1UtilsTestPingGetResponse = ({
    [key: string]: unknown;
});