"""Add tianchou optimization tables

Revision ID: 37a225de506c
Revises: bfb9cc922d8a
Create Date: 2026-02-12 11:20:58.637991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37a225de506c'
down_revision = 'bfb9cc922d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry_type', sa.Enum('LIGHT', 'HEAVY', name='industrytype'), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('pareto_solution_count', sa.Integer(), nullable=False),
    sa.Column('recommended_solution_id', sa.Uuid(), nullable=True),
    sa.Column('weights_cost', sa.Float(), nullable=True),
    sa.Column('weights_time', sa.Float(), nullable=True),
    sa.Column('weights_benefit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_tasks_name'), 'optimization_tasks', ['name'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('ahp_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consistency_ratio', sa.Float(), nullable=False),
    sa.Column('best_solution_id', sa.Uuid(), nullable=True),
    sa.Column('decision_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['optimization_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_task_id'), 'decision_records', ['task_id'], unique=False)
    op.create_table('pareto_solutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('f2', sa.Float(), nullable=False),
    sa.Column('f3', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('implementation_days', sa.Float(), nullable=False),
    sa.Column('expected_benefit', sa.Float(), nullable=False),
    sa.Column('solution_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('topsis_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['optimization_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pareto_solutions_task_id'), 'pareto_solutions', ['task_id'], unique=False)
    op.drop_constraint(op.f('stations_line_id_fkey'), 'stations', type_='foreignkey')
    op.create_foreign_key(None, 'stations', 'production_lines', ['line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.create_foreign_key(op.f('stations_line_id_fkey'), 'stations', 'production_lines', ['line_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pareto_solutions_task_id'), table_name='pareto_solutions')
    op.drop_table('pareto_solutions')
    op.drop_index(op.f('ix_decision_records_task_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_optimization_tasks_name'), table_name='optimization_tasks')
    op.drop_table('optimization_tasks')
    # ### end Alembic commands ###
