"""add evolution_history to optimization_tasks

Revision ID: 7aa942b12897
Revises: 37a225de506c
Create Date: 2026-02-16 14:39:27.557415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aa942b12897'
down_revision = '37a225de506c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_tasks', sa.Column('evolution_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimization_tasks', 'evolution_history')
    # ### end Alembic commands ###
