"""add diagnosis table and update solution table

Revision ID: a51268ebac7b
Revises: a9bad07b2d87
Create Date: 2026-01-12 22:01:32.638042

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a51268ebac7b'
down_revision = 'a9bad07b2d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('anomaly_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('solutions', sa.Column('diagnosis_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'solutions', 'diagnoses', ['diagnosis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solutions', type_='foreignkey')
    op.drop_column('solutions', 'diagnosis_id')
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
