"""fix relationship mapping between production_lines and stations

Revision ID: bfb9cc922d8a
Revises: a51268ebac7b
Create Date: 2026-01-12 22:05:27.445145

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bfb9cc922d8a'
down_revision = 'a51268ebac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key constraints
    op.drop_constraint('stations_line_id_fkey', 'stations', type_='foreignkey')

    # Recreate foreign key with proper cascade options
    op.create_foreign_key(
        'stations_line_id_fkey',
        'stations',
        'production_lines',
        ['line_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new foreign key constraint
    op.drop_constraint('stations_line_id_fkey', 'stations', type_='foreignkey')

    # Recreate the original foreign key constraint
    op.create_foreign_key(
        'stations_line_id_fkey',
        'stations',
        'production_lines',
        ['line_id'],
        ['id']
    )
    # ### end Alembic commands ###
